# Generated by Django 4.1.5 on 2023-04-09 17:39

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificates",
            name="file",
            field=models.FileField(upload_to=home.models.user_directory_path),
        ),
    ]
